name: Lint

on:
  push:
    branches:
    - feature/*
    - ci-tests
  pull_request:
    branches:
      - ci-tests

jobs:
  lint_iOS:
    name: Lint iOS frameworks
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install fastlane
        run: |
          brew install fastlane
      - name: Linting 
        run: fastlane run swiftlint config_file:".swiftlint.yml"
  